### ISSUE TITLE
Error with vtcmd --warning

### ISSUE THREAD

**Issue by sean-cho** [NDAR/nda-tools#2]
Running `vtcmd` with the `-w` argument fails to execute properly, see below.

```
vtcmd genomics_subject02.csv nichd_btb02.csv genomics_sample03.csv -w

Traceback (most recent call last):
  File "/users/swengcho/.conda/envs/cloud/bin/vtcmd", line 10, in <module>
    sys.exit(main())
  File "/users/swengcho/.conda/envs/cloud/lib/python3.7/site-packages/NDATools/clientscripts/vtcmd.py", line 257, in main
    validation_results = validate_files(args.files, w, bp, threads=args.workerThreads, config=config)
  File "/users/swengcho/.conda/envs/cloud/lib/python3.7/site-packages/NDATools/clientscripts/vtcmd.py", line 160, in validate_files
    validation.warnings()
AttributeError: 'Validation' object has no attribute 'warnings'
```

The issue is traceable here;

https://github.com/NDAR/nda-tools/blob/4a8461e6367bb8672fffc6e41dcbcce8be6efde8/nda-tools-python/NDATools/clientscripts/vtcmd.py#L160

Based on the validation object defined by Validation.py, this should be ` validation.get_warnings()`

**Comment by ushnaahmad** [comment]
Hi @sean-cho 

Thank you for reporting the error. We will be releasing an updated version of nda-tools some time next week and will make sure correct the issue for that release. I'll let you know when it is up. 

Thanks again!

**Comment by sean-cho** [comment]
Hi @ushnaahmad 

Thanks for getting back to me. I've made that change on my local copy and it works well.

I appreciate your work developing this tool -- it's great and really helpful! Looking forward to the update.

Thanks!
