### ISSUE TITLE
Vtcmd feature request:  Add option to hide progress monitor

### ISSUE THREAD

**Issue by hodgem** [NDAR/nda-tools#3]
I've run into failures relating to the progress monitor in the Linux environment.  Vtcmd submissions work fine from the command line but fail when launched from Java's Runtime environment.  The issue could be fixed by setting the "ascii" option to true for all operating systems (currently it's "ascii=os.name == 'nt'"), however it would be preferable to have an option to hide the progress monitors.  I've coded the option for our internal use, along with some improvements to outcome reporting when hiding the progress monitor, here:

https://github.com/hodgem/nda-tools/commits/ccf_customizations

I'm thinking it might be useful to others to have this option as well.  Thanks!

**Comment by ushnaahmad** [comment]
Hi @hodgem, 
Thank you so much for sharing your edits. We will pull and review the changes and plan to merge with an upcoming release.
