### ISSUE TITLE
NDA Downloads/File Deletions

### ISSUE THREAD

**Issue by JBarsotti** [NDAR/nda-tools#35]
Hello again!

Sorry to bother you with yet another question.

If I would like to download data from the NDA website using the commands given in the ReadMe section of NDA-Tools, do I need an AWS account? It looks like that is the best way. But wanted to ask.

Also, if I ever want to delete a previously uploaded file (for instance, it is a duplicate of another uploaded file), is there a way to do this, as well?

Thanks again for all your help,

John

**Comment by aburr-nimh** [comment]
Good morning, I believe I can answer one of your questions, but I require clarification on another. Let's start with what I can answer:

> If I would like to download data from the NDA website using the commands given in the ReadMe section of NDA-Tools, do I need an AWS account?

Using the download command provided in NDA Tools you do not need an AWS account to download data, only the id of the package you want to download and an NDA account with permission to access that data.  

Now, for the one that I need some clarification on:

> Also, if I ever want to delete a previously uploaded file (for instance, it is a duplicate of another uploaded file), is there a way to do this, as well?

I'm not sure what you mean by "previously uploaded file" as that's rather vague, do you mean an uploaded associated file or an entire data submission?

**Comment by JBarsotti** [comment]
Thank you so much for your reply!

When I say "previously uploaded file," I am referring to a data submission that I have done multiple times that I would like to delete. It is a very small submission that I used basically as a test case to see whether it would work. So it has already been uploaded to the NDA website.

Thanks again!

John

**Comment by gregmagdits** [comment]
Hello,
   At the moment there is no way to delete a submission from the UI - In order to do this you need to put in a request with the Help Desk (https://ndar.zendesk.com/agent ). Once a ticket is open, NDA staff will need to archive the submission that you want to delete, which will prevent the data from being shared

**Comment by JBarsotti** [comment]
Okay. Thank you for the reply, Greg!
