### ISSUE TITLE
`-s3` is useless

### ISSUE THREAD

**Issue by AKSoo** [NDAR/nda-tools#39]
Despite supposedly being the "preferred" method of downloading data, `-s3` is utterly useless because the downloaded files are owned by NDA. This blocks the bucket owner (user) from doing almost anything with the files.

The solution is applying `--acl bucket-owner-full-control` during the s3-to-s3 copy.

See https://stackoverflow.com/questions/34055084/s3-user-cannot-access-object-in-his-own-s3-bucket-if-created-by-another-user

**Comment by gregmagdits** [comment]
Unfortunately you were right and setting the acl was overlooked in the release of the -s3 functionality. We released a hotfix today with version 0.2.13 which sets the 'bucket-owner-full-control' option. (commit https://github.com/NDAR/nda-tools/commit/d7e2a8fb05d4bc18aa137b5672603ea7a60038e4)

For users who have already downloaded using the -s3 option, there are 2 options for correct the issue:
1. you can delete the objects and re-run the download using the 0.2.13 version of the nda-tools client. 
2. If you prefer not to restart the download, you can open a Help Desk ticket (email 'NDAHelp@mail.nih.gov' or go to https://ndar.zendesk.com) and we can run a script to fix the acl on the objects in your account.
