### ISSUE TITLE
Validating files frozen, no errors or updates

### ISSUE THREAD

**Issue by evansorenson** [NDAR/nda-tools#41]
I'm submitting eeg_sub_files01 data with manifest files. This is the command I am calling.
`vtcmd eeg_sub_files01.txt -m ./manifest -l ./BIDS -t {title}  -d {description} -c {COLLECTION_ID} -b`

This is the output. Nothing seems to happen ever and I don't get any error messages.
```
Validating files...
  0%|                                                                                        | 0/1 [00:00<?, ?it/s]
```

**Comment by gregmagdits** [comment]
it would be helpful to see the file that is being uploaded. Instead of posting the file here, please open a Help Desk Ticket (https://ndar.zendesk.com). We can troubleshoot the issue in that forum and post the resolution here for reference in case other users encounter a similar issue in the future
