### ISSUE TITLE
Where does vtcmd install to?

### ISSUE THREAD

**Issue by jawaltz** [NDAR/nda-tools#42]
Even when installation seemed to succeed, I get a "command not found" for vtcmd, and I don't see a folder in any of the obvious places. What am I looking for, and where am I looking for it?

**Comment by WillForan** [comment]
you might need to update your shell's `$PATH` to include the directory pip installed the script to. e.g. add `export PATH=$PATH:$HOME/.local/bin` to `~/.bashrc`

 `pip show --files nda-tools` might be helpful.
![image](https://github.com/NDAR/nda-tools/assets/680742/bb24af16-8357-4d3b-bd28-6b77faa6b497)

**Comment by gregmagdits** [comment]
similar to https://github.com/NDAR/nda-tools/issues/63
