### ISSUE TITLE
If my file upload was disrupted, can I cancel it, or delete the process?

### ISSUE THREAD

**Issue by jawaltz** [NDAR/nda-tools#43]
Are there any other options for

vtcmd <submissionID> -r

?

I don't want to RESUME my submission; I want to CANCEL it. I already completed it under a separate submissionID.

**Comment by gregmagdits** [comment]
Going through some old tickets and adding answers in case it helps others who come across similar issues. There is no way to cancel a submission. If a submission was not completed, then the user doesnt need to do anything....submissions that have not finished uploading do not get shared. If a submission was completely uploaded and some data in the submission needs to be edited, then you need to email ndahelp@mail.nih.gov which will authorize the submission to be replaced. After the submission has been authorized to be replaced, you can use the -rs flag in the tools to replace the submission. 

Instructions for using the HTML and nda-tools to replace a submission can be found here - https://s3.amazonaws.com/nda.nih.gov/Documents/Tutorials/HowToProvideCorrectedFiles.pdf
