### ISSUE TITLE
ABCD MRI data downloading issue

### ISSUE THREAD

**Issue by fullcream9** [NDAR/nda-tools#44]
Hi experts,

I try to download ABCD MRI data using NDA-tools downloadcmd script.
Following https://github.com/ABCD-ReproNim/exercises/blob/main/project_month_prep/downloadMRI.md All steps above were successful. But it comes to this downloading step:

! mkdir /home/jovyan/ABCDndar/tar_files
! downloadcmd -dp <project-id> -d '/home/jovyan/ABCDndar/tar_files' -u <NDA-username> -p <NDA-password> -t '/home/jovyan/ABCDndar/s3_derv_links_5subj.txt'

Now s3_derv_links_5subj.txt contains five s3 links.

![20220722165106](https://user-images.githubusercontent.com/77040806/180630852-180dc74d-8300-4286-b05c-6cb334744bbc.png)

1. What is <project-id> here? how to get it?
2. Are AWS Credentials required? how to get it?

Cheers~
Thank you!

**Comment by gregmagdits** [comment]
Hello,
  The links you have in the s3_derv_links_5subj.txt have the incorrect path. i.e. you will need to remove the extra 's3:/' before the abcd-mproc-release4 in each of the file-paths.
   The value of the -dp argument is the package-id, not the project id. The package-id is the id of the package that contains your files. You should be able to see the package-ids if you login to the website and click on the 'packages' tab.
   You do not need aws credentials to download your files using this new tool. We are in the process of updating our tutorials to make this more clear. (The tutorials currently describe the original way of obtaining files from NDA which has changed a number of years ago)
