### ISSUE TITLE
Check for symlinks and option to force derefencing

### ISSUE THREAD

**Issue by Shotgunosine** [NDAR/nda-tools#5]
I'm not sure what the current behavior of vtcmd is with respect to symlinks, but if it does not already deference symlinks when uploading files, it would be a useful feature. Often we have prepared the source files and named the base directory for internal organization in a way that looks messy or confusing for data users and we'd like to be able to use symlinks to manage that.

**Comment by ushnaahmad** [comment]
Hello @Shotgunosine ,

I have tested vtcmd with symlinks in MacOS and it is able to locate and upload files successfully. I believe Linux would have similar results as they are both Unix-like operating systems. I have not tested this in Windows, which works with symlinks a bit differently. If your data is in Mac or Linux, then you should be good to try and upload with symlinks. If not, let me know, and I can create a ticket to test and update symlinks for Windows.

**Comment by sean-cho** [comment]
I had the same question and came across this. I can confirm that vtcmd dereferences symlinks on CentOS 6.5. Furthermore, the directory structure on the S3 bucket takes on the symlinked structure.

**Comment by Shotgunosine** [comment]
Thanks for looking into this. Good to know and I'm glad it works.
