### ISSUE TITLE
Command 'vtcmd' not found

### ISSUE THREAD

**Issue by gbook** [NDAR/nda-tools#63]
I'm working on Ubuntu 18.04 (wsl on Windows)

I install NDA tools using the following command
`pip3 install nda-tools`

It installs successfully, but I can't run the `vtcmd` command. What am I missing?

**Comment by gregmagdits** [comment]
What is the error message that you are seeing ?

**Comment by AhaTree** [comment]
I have the same issue, I tried to run
 `vtcmd -h`
, it raises "Command 'vtcmd' not found". 
I run
`downloadcmd -h`
, it raises Command 'downloadcmd' not found,

**Comment by gregmagdits** [comment]
try running:
python -m NDATools.clientscripts.vtcmd -h
python -m NDATools.clientscripts.downloadmd -h

**Comment by jacob-lee** [comment]
To eliminate the possibility that a different `pip` is being used to install nda tools, I recommend doing the install this way:

```
python -m pip install nda-tools
```

per recommendation in the docs:

https://docs.python.org/3/installing/index.html

**Comment by AhaTree** [comment]
> try running: python -m NDATools.clientscripts.vtcmd -h python -m NDATools.clientscripts.downloadmd -h

It worked! Thanks!
