### ISSUE TITLE
Version out of date

### ISSUE THREAD

**Issue by cjl2007** [NDAR/nda-tools#65]
Hi - I received this error, 

Running NDATools Version 0.2.24
Your version of nda-tools is out of date. Please upgrade to the latest version (0.2.25) from PyPi or GitHub and try again. 
	To upgrade using pip, run: 
pip install nda-tools==0.2.25

I ran the suggested line of code 

sudo pip install nda-tools==0.2.25

No errors (that I can tell). 

Requirement already satisfied: nda-tools==0.2.25 in /usr/local/lib/python3.8/dist-packages (0.2.25)
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from nda-tools==0.2.25) (2.22.0)
Requirement already satisfied: keyring in /usr/lib/python3/dist-packages (from nda-tools==0.2.25) (18.0.1)
Requirement already satisfied: pyyaml in /usr/lib/python3/dist-packages (from nda-tools==0.2.25) (5.3.1)
Requirement already satisfied: botocore in /usr/lib/python3/dist-packages (from nda-tools==0.2.25) (1.16.19)
Requirement already satisfied: tqdm in /usr/lib/python3/dist-packages (from nda-tools==0.2.25) (4.30.0)
Requirement already satisfied: mock in /usr/lib/python3/dist-packages (from nda-tools==0.2.25) (3.0.5)
Requirement already satisfied: packaging in /root/.local/lib/python3.8/site-packages (from nda-tools==0.2.25) (23.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (from nda-tools==0.2.25) (2.0.1)
Requirement already satisfied: boto3 in /root/.local/lib/python3.8/site-packages (from nda-tools==0.2.25) (1.26.123)
Requirement already satisfied: secretstorage in /usr/lib/python3/dist-packages (from keyring->nda-tools==0.2.25) (2.3.1)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas->nda-tools==0.2.25) (1.24.3)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas->nda-tools==0.2.25) (2023.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas->nda-tools==0.2.25) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas->nda-tools==0.2.25) (2023.3)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /usr/lib/python3/dist-packages (from boto3->nda-tools==0.2.25) (0.9.4)
Requirement already satisfied: s3transfer<0.7.0,>=0.6.0 in /root/.local/lib/python3.8/site-packages (from boto3->nda-tools==0.2.25) (0.6.0)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.8.2->pandas->nda-tools==0.2.25) (1.14.)

But when I go to run the command I still get the same error re: version, suggesting I have not successfully upgraded nda tools to 0.2.25 after all. 

by the way, If i run without the sudo prompt (pip install nda-tools==0.2.25), I get this error 
Building wheels for collected packages: pandas
  WARNING: Building wheel for pandas failed: [Errno 13] Permission denied: '/home/charleslynch/.cache/pip/wheels/5c'
Failed to build pandas
ERROR: Could not build wheels for pandas which use PEP 517 and cannot be installed directly

**Comment by cjl2007** [comment]
I uninstalled the previous version and now it works fine

pip uninstall nda-tools==0.2.24

**Comment by jacob-lee** [comment]
I wonder if you were inadvertently working with two python environments. One of the problems with using `pip` directly, instead of calling it like `python -m pip` is that the `pip` that comes up on your path may not correspond to the python on your path.

**Comment by lauragails** [comment]
Hello, 
I am getting this issue when I install with pip or from the github directly: 

`python nda-tools/NDATools/clientscripts/vtcmd.py -h`

```
Running NDATools Version 0.2.25
Your version of nda-tools is out of date. Please upgrade to the latest version (0.2.27) from PyPi or GitHub and try again.
	To upgrade using pip, run:
pip install nda-tools==0.2.27
```
