### ISSUE TITLE
Downloadcmd issues

### ISSUE THREAD

**Issue by ZhenyaoYe** [NDAR/nda-tools#75]
Hi, 

I got the following keyring.errors using downloadcmd, any suggestion are appreciated! 

keyring.errors.NoKeyringError: No recommended backend was available. Install a recommended 3rd party backend package; or, install the keyrings.alt package if you want to use the non-recommended backends. See https://pypi.org/project/keyring for details.

Best regards,
Zhenyao

**Comment by gregmagdits** [comment]
Keyring is not necessary for NDA-tools to work. You can disable it by following the instructions in the "Disabling Keyring" section of https://pypi.org/project/keyring. If you are on MAC or linux, you can do this by running 
`export PYTHON_KEYRING_BACKEND=keyring.backends.null.Keyring`
in the terminal and then running the nda-tools command in the same terminal session.

**Comment by ZhenyaoYe** [comment]
Your assistance was greatly appreciated! The issue has been resolved.
