### ISSUE TITLE
ClientConfiguration misreports location of settings.cfg

### ISSUE THREAD

**Issue by dmd** [NDAR/nda-tools#79]
It took me an awfully long time to debug something, because `ClientConfiguration` misreports the location of the `settings.cfg` it uses.

If the `-u/--username` argument is not provided, [downloadcmd prints](https://github.com/NDAR/nda-tools/blob/aa89ec26de21f04679dec702c054f19ef48726d4/NDATools/Configuration.py#L88) something like:

```
-u/--username argument not provided. Using default value of 'johnsmith' which was saved in /home/jsmith/.NDATools/settings.cfg
```

However, that may not be true, if [this else statement](https://github.com/NDAR/nda-tools/blob/aa89ec26de21f04679dec702c054f19ef48726d4/NDATools/Configuration.py#L65) triggered.

**Comment by dmd** [comment]
#80 is a simple PR to resolve this.

**Comment by nicholst** [comment]
I too noticed this; when I omit the `-u` option it tells me

```
-u/--username argument not provided. Using default value of 'JOESMITH' which was saved in /Users/joesmith/.NDATools/settings.cfg
```

but then later, when I was having problems logging in told me

```
The password that was entered for user 'JOESMITH' is invalid ...
If your username was previously entered incorrectly, you may update it in your settings.cfg located at 
/Users/joesmith/anaconda3/envs/py3/lib/python3.11/site-packages/NDATools/clientscripts/config/settings.cfg
Enter your NIMH Data Archives password:
```

and it is, indeed, in that later location deep in my anaconda install.

**Comment by dmd** [comment]
It is an additional bug that downloadcmd would be altering a file in `site-packages`.  Programs should not be altering files in their installation like that!

**Comment by gregmagdits** [comment]
This has been addressed in the most recent version of the tools, 0.2.26. We also modified the logic so that the client doesn't attempt to modify the files in the site-packages dir, as @dmd  pointed out above.
