### ISSUE TITLE
unnecessary sleeps in Download.py

### ISSUE THREAD

**Issue by dmd** [NDAR/nda-tools#81]
There are two `time.sleep` calls that run on every `downloadcmd`:

https://github.com/NDAR/nda-tools/blob/aa89ec26de21f04679dec702c054f19ef48726d4/NDATools/Download.py#L238

https://github.com/NDAR/nda-tools/blob/aa89ec26de21f04679dec702c054f19ef48726d4/NDATools/Download.py#L271

Are these necessary? We are writing automated tools which, as their first step, download a subset of a particular participant's files into a working space, using s3-to-s3 transfer, and those 6.5 seconds of sleep are 20% of the time the entire downloadcmd takes to run.

**Comment by gregmagdits** [comment]
No, they are just there to make the output from the program easier to read. We'll see if we can make make these configurable in the next release of this tool, which we are aiming to deploy in the next couple of weeks. If you are already customizing the code, feel free to remove these lines for now. If not and you cannot wait 2 weeks, we can deploy a preview version of the release with the necessary change to testpypi

**Comment by dmd** [comment]
Thanks. This can certainly wait a couple weeks, there's plenty of even lower-hanging fruit for me to optimize.

**Comment by dmd** [comment]
What is the status of the new release?

**Comment by gregmagdits** [comment]
We do not have a specific release date yet but I expect this will take another week or 2. The pre-release is available now at testpypi and you can install it by running

pip install -i https://test.pypi.org/simple/ nda-tools==0.2.26.dev7 

0.2.26.dev7 does not address this github issue but we can have a fix for this deployed to testpypi in the next day or two
