### ISSUE TITLE
Number of files in package is 0

### ISSUE THREAD

**Issue by Becmamba** [NDAR/nda-tools#86]
![image](https://github.com/NDAR/nda-tools/assets/33661291/97393c6f-be27-4617-878a-4708f489703f)

Total package size is very large, but the number of files in package is 0. What is the problem?

**Comment by gregmagdits** [comment]
There is a data issue that the team is working to try to resolve now. We will post an update when the fix has been made.

**Comment by gregmagdits** [comment]
The fix for this has been deployed. You will need to delete the package_file_metadata.txt.gz and package_file_metadata.txt files that were downloaded before rerunning the command.
