### ISSUE TITLE
An unexpected error was encountered and the program could not continue. Error message from service was: {'timestamp': '2023-12-04T05:16:24.481+00:00', 'status': 409, 'error': 'Conflict', 'path': '/api/packaging-ws/113460/create-package-metadata-file'}

### ISSUE THREAD

**Issue by racheldaydayup** [NDAR/nda-tools#87]
I get this error when downloading the package：

(pytorch) C:\Users\downloadcmd -dp 113460 -d E:/datasets/112
Running NDATools Version 0.2.25
-u/--username argument not provided. Using default value of 'xxxxxx' which was saved in C:\Users\.NDATools\settings.cfg

No value specified for --workerThreads. Using the default option of 19
Important - You can configure the thread count setting using the --workerThreads argument to maximize your download speed.

Getting Package Information...

Package-id: 113460
Name: OAI12MonthImages
Has associated files?: Yes
Number of files in package: 6
Total Package Size: 814.22GB

Getting list of all files in package at 13:16:29 ....
This is a one time operation that will take about 1 min for every 1 million files in your package.
Your download will start after this process completes....

An unexpected error was encountered and the program could not continue. Error message from service was:
{'timestamp': '2023-12-04T05:16:24.481+00:00', 'status': 409, 'error': 'Conflict', 'path': '/api/packaging-ws/113460/create-package-metadata-file'}

Exit signal received, shutting down...

**Comment by gregmagdits** [comment]
This was an issue with one of the underlying services that has since been resolved. You should not see this issue if you re-run the command.
