### ISSUE TITLE
downloadcmd 403 error

### ISSUE THREAD

**Issue by fullcream9** [NDAR/nda-tools#91]
![image](https://github.com/NDAR/nda-tools/assets/77040806/a3f1f71f-fcff-4f03-b21d-d8577f5afd5)

I use downloadcmd to download packages on NDA, just now it was fine, but a small part of the file failed to download, re now it's a 403 error

I'm looking for guidance. Thanks in advance!

**Comment by gregmagdits** [comment]
Please login to NDAR and check on the status of the package. The 403 error code indicates that the package might have been archived. If so, you will need to create a new package to download the files.

**Comment by fullcream9** [comment]
think you!
