### ISSUE TITLE
File "NA" not found

### ISSUE THREAD

**Issue by mjschneider42** [NDAR/nda-tools#93]
Hi there,

I am pretty new to python and need to use the NDA python upload tool for some fMRI data. I have gotten through the validation process with no errors and am now into uploading associated imaging files. Everything is fine except I keep getting the following message:

![error_message](https://github.com/NDAR/nda-tools/assets/163488528/cbc75d50-f285-4da1-9091-a7c5bfb8977b)

I cleaned my image03 file and made sure there were no missing or empty cells in the "image_file" variable, and I even made a file called "NA" to see if that would fix the issue. Any ideas on what might be happening here? 

Thanks so much!

**Comment by gregmagdits** [comment]
I expect one of the rows has a value of 'NA' for image_file or manifest. Please open a help desk ticket by emailing ndahelp@mail.nih.gov and attach your image03.csv file to the email. We will take a look at the file for you

**Comment by mjschneider42** [comment]
Thanks so much!
